net-p2p/rtorrent: Revision bump to 0.9.6-r1
- Update copyright
- Includes ::gentoo patches
- Fixes undefined reference to
  `bool std::isprint<char>(char, std::locale const&)'

Package-Manager: Portage-3.0.13, Repoman-3.0.2